// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PerformanceReview.Data.EntityFramework;
using System;

namespace PerformanceReview.Web.Rest.Migrations
{
    [DbContext(typeof(PerformanceReviewContext))]
    [Migration("20171104144826_Refactor_Remove_One_To_One")]
    partial class Refactor_Remove_One_To_One
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.AssignedReviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreTime");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("EmployeeReviewId");

                    b.Property<DateTime>("ModTime");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeReviewId");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreTime");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("JobTitle");

                    b.Property<DateTime>("ModTime");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.EmployeeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aspirations");

                    b.Property<string>("Communications");

                    b.Property<DateTime>("CreTime");

                    b.Property<string>("DeliveringResults");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("Leadership");

                    b.Property<DateTime>("ModTime");

                    b.Property<string>("Objectives");

                    b.Property<string>("OverallPerformance");

                    b.Property<string>("TechnicalPerformance");

                    b.HasKey("Id");

                    b.ToTable("EmployeeReviews");
                });

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreTime");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("EmployeeReviewId");

                    b.Property<DateTime>("ModTime");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeReviewId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.AssignedReviewer", b =>
                {
                    b.HasOne("PerformanceReview.Data.EntityFramework.Entity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PerformanceReview.Data.EntityFramework.Entity.EmployeeReview", "EmployeeReview")
                        .WithMany()
                        .HasForeignKey("EmployeeReviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PerformanceReview.Data.EntityFramework.Entity.Feedback", b =>
                {
                    b.HasOne("PerformanceReview.Data.EntityFramework.Entity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PerformanceReview.Data.EntityFramework.Entity.EmployeeReview", "EmployeeReview")
                        .WithMany("Feedback")
                        .HasForeignKey("EmployeeReviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
